{
  "modified": "2025-10-23T19:17:22Z",
  "published": "2025-10-23T19:17:22Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2025-47813"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "worldnex"
      },
      "versions": [
        "1.1.0",
        "2.0.0",
        "2.0.1"
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/worldnex/MAL-2025-47813.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "547bfc641fa3fdf5d3e96968cb590b62654032a00c0e366f5420418bc2f6cd7a",
        "import_time": "2025-10-27T18:09:10.150223617Z",
        "id": "RLUA-2025-05230",
        "modified_time": "2025-10-23T19:17:22Z",
        "versions": [
          "1.1.0",
          "2.0.0",
          "2.0.1"
        ]
      }
    ]
  }
}
